### Bag of Words

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "He is a good boy",
    "She is a good girl",
    "Boy and girl are good"
]

vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['boy' 'girl' 'good']
[[1 0 1]
 [0 1 1]
 [1 1 1]]


In [1]:
import numpy, gensim
print("NumPy:", numpy.__version__)
print("Gensim:", gensim.__version__)
from gensim.models import KeyedVectors  # should import cleanly


RuntimeError: Compiled extensions are unavailable. If you've installed from a package, ask the package maintainer to include compiled extensions. If you're building Gensim from source yourself, install Cython and a C compiler, and then run `python setup.py build_ext --inplace` to retry. 

In [ ]:
import gensim.downloader as api

model = api.load("word2vec-google-news-300")
print(model.most_similar("king"))
# [('queen', 0.7118), ('monarch', 0.6186), ...]


ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject